version: '3.3'

services:
  gateway:
    build: gateway
    image: gateway
    container_name: gateway
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    ports:
      - "8080:8080"
    networks:
      - frontend
    env_file:
      - .env
    depends_on:
      - server

  server:
    build: server
    image: server
    container_name: server
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    ports:
      - "9090:9090"
    networks:
      - frontend
      - backend
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine3.18
    container_name: PostgreSQL
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
    ports:
      - "6541:5432"
    networks:
      - backend
    env_file:
      - .env

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  databases:
    driver: bridge