spring:
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: validate
#      ddl-auto: create
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: TRUE
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: postgres
    password: postgres
