-- drop all tables

--drop table if exists public.bookings cascade;
--drop table if exists public.comments cascade;
--drop table if exists public.items cascade;
--drop table if exists public.requests cascade;
--drop table if exists public.users cascade;

-- public.users definition

create table if not exists public.users (
  id int generated by default as identity not null primary key,
   email varchar(255) unique,
   name varchar(255)
);

-- public.requests definition

create table if not exists public.requests (
  id int generated by default as identity not null primary key,
   created date,
   description varchar(2000),
   requester int references public.users (id)
);

-- public.items definition

create table if not exists public.items (
  id int generated by default as identity not null primary key,
   name varchar(255),
   description varchar(255),
   available boolean not null,
   owner_id int references public.users (id)
);

-- public.requests definition

create table if not exists public.comments (
  id int generated by default as identity not null primary key,
   comment_text varchar(512),
   item_id int references public.items (id),
   author_id int references public.users (id)
);

-- public.bookings definition

--create type booking_status as enum ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');

create table if not exists public.bookings (
  id bigint generated by default as identity not null primary key,
   start_time timestamp without time zone not null,
   break_time timestamp without time zone not null,
   item_id int references public.items (id),
   booker_id int references public.users (id),
   status varchar(10) default 'WAITING'
);