server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: validate

  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    jpa:
      properties:
        hibernate.format_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}