-- drop all tables

--drop table if exists public.bookings cascade;
--drop table if exists public.comments cascade;
--drop table if exists public.items cascade;
--drop table if exists public.requests cascade;
--drop table if exists public.users cascade;

-- public.users definition

create table if not exists public.users (
  id bigint generated by default as identity not null primary key,
   email varchar(255) not null unique,
   name varchar(255) not null
);

-- public.requests definition

create table if not exists public.requests (
  id bigint generated by default as identity not null primary key,
   created timestamp without time zone not null,
   description varchar(2000),
   requester_id bigint references public.users (id) on DELETE cascade
);

-- public.items definition

create table if not exists public.items (
  id bigint generated by default as identity not null primary key,
   name varchar(255),
   description varchar(512),
   available boolean not null,
   owner_id bigint references public.users (id),
   item_request_id bigint references public.requests (id)
);

-- public.comments definition

create table if not exists public.comments (
  id bigint generated by default as identity not null primary key,
   text varchar(2048),
   item_id bigint references public.items (id) on DELETE cascade,
   author_id bigint references public.users (id) on DELETE cascade,
   created timestamp without time zone not null
);

-- public.bookings definition

--create type booking_status as enum ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');

create table if not exists public.bookings (
  id bigint generated by default as identity not null primary key,
   start_time timestamp without time zone not null,
   break_time timestamp without time zone not null,
   item_id bigint references public.items (id),
   booker_id bigint references public.users (id),
   status varchar(10) default 'WAITING'
);